services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8228:8080
    volumes:
      # - ./:/app
      - type: bind
        source: .
        target: /app
